@startuml
[*] --> DISCHARGING_PASSIVE
DISCHARGING_PASSIVE --> DISCHARGING_ACTIVE: 1
DISCHARGING_PASSIVE --> CHARGING: 2
DISCHARGING_PASSIVE --> UNDERVOLTAGE_PROTECTION: 5
DISCHARGING_ACTIVE --> CHARGING: 2
DISCHARGING_ACTIVE --> UNDERVOLTAGE_PROTECTION: 5
UNDERVOLTAGE_PROTECTION --> CHARGING: 2
CHARGING --> DISCHARGING_PASSIVE: 6
CHARGING --> OVERLOAD_PROTECTION: 3
CHARGING --> CHARGE_STOP_BC_TEMP: 4
CHARGE_STOP_BC_TEMP --> CHARGING: 7
OVERLOAD_PROTECTION --> CHARGING: 6
@enduml
